title: "Orion Miller" #tab title
author: "Orion Miller" #name appearing at top of header
description: "© 2022-2024 Orion Miller" #text for footer
permalink: /:title/
lang: "en"
excerpt_separator: <!-- excerpt-end -->
date_format: "%B %d, %Y"

# Layout
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

paginate: 10 # number of items per page in Posts section
highlighter: rouge #code syntax highlighter

#property for main url - to try and force links to be https
url: https://orion-miller.github.io

# Nav Bar Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "About.md"} 
  - {file: "index.html"} 
  # - {url: "https://orion-miller.github.io/cv/", title: "CV"} #dir created by embedCV.html in assets/resume_cv
  - {title: "CV", file: "embedCV.html"}  
  - {title: "Footprints", file: "footprints.html"}
  # - {url: "assets/resume_cv/20220409_Resume_Orion_Miller.pdf", title: CV Download} 

# Footer
external:                  # shows social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:orion.miller@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/orion-miller"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/orionmmiller/"}

comments:
 - disqus_shortname: "orionmiller"    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

plugins:
 - jekyll-feed
